services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=game
  game:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/exchange_api
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: