"""game_models migration

Revision ID: 1cc7bc5d4d99
Revises: 61bb2e78f168
Create Date: 2022-03-14 17:55:10.787736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc7bc5d4d99'
down_revision = '61bb2e78f168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
