"""game_models migration

Revision ID: 1f2a89976155
Revises: 5e2b2b060b10
Create Date: 2022-03-13 18:02:53.413311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2a89976155'
down_revision = '5e2b2b060b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
