"""game_models migration

Revision ID: 2207c7bd0a72
Revises: 101af0c4268c
Create Date: 2022-03-13 16:59:15.138909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2207c7bd0a72'
down_revision = '101af0c4268c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
