"""game_models migration edited

Revision ID: 3397e1bb5431
Revises: d50d5f588587
Create Date: 2022-02-26 17:19:43.384969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3397e1bb5431'
down_revision = 'd50d5f588587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('diff', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_of_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_users')
    op.drop_table('development')
    op.add_column('securities', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('securities', sa.Column('code', sa.String(), nullable=False))
    op.drop_column('securities', 'start_cost')
    op.add_column('securities_for_game', sa.Column('code', sa.String(), nullable=False))
    op.alter_column('user', 'create_at',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('securities_for_game', 'code')
    op.add_column('securities', sa.Column('start_cost', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('securities', 'code')
    op.drop_column('securities', 'cost')
    op.create_table('development',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diff', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='development_pkey')
    )
    op.create_table('game_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='game_users_game_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='game_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='game_users_pkey')
    )
    op.drop_table('users_of_game')
    op.drop_table('event')
    # ### end Alembic commands ###
