"""game_models migration

Revision ID: 3db943d9cfc9
Revises: 4ce0b9e055ca
Create Date: 2022-03-13 17:54:44.923799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db943d9cfc9'
down_revision = '4ce0b9e055ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'securities', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'securities', type_='unique')
    # ### end Alembic commands ###
