"""game_models migration

Revision ID: 49adf5e536a5
Revises: b96d496f47f2
Create Date: 2022-03-14 18:09:34.232296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49adf5e536a5'
down_revision = 'b96d496f47f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
