"""game_models migration

Revision ID: 4ce0b9e055ca
Revises: a7d0c2af2f58
Create Date: 2022-03-13 17:47:30.025054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce0b9e055ca'
down_revision = 'a7d0c2af2f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
