"""game_models migration

Revision ID: 4f640117fe5a
Revises: 2207c7bd0a72
Create Date: 2022-03-13 16:59:59.431564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f640117fe5a'
down_revision = '2207c7bd0a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
