"""game_models migration

Revision ID: 50b571ea3c4d
Revises: 49adf5e536a5
Create Date: 2022-03-14 18:12:23.899833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b571ea3c4d'
down_revision = '49adf5e536a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
