"""game_models migration

Revision ID: 5e2b2b060b10
Revises: 3db943d9cfc9
Create Date: 2022-03-13 17:55:50.720915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2b2b060b10'
down_revision = '3db943d9cfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
