"""game_models migration

Revision ID: 61bb2e78f168
Revises: f69bf3064453
Create Date: 2022-03-14 17:52:49.593533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61bb2e78f168'
down_revision = 'f69bf3064453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
