"""game_models migration

Revision ID: 7778d3dfc816
Revises: 8eafbc33d0f6
Create Date: 2022-03-14 18:25:42.872179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7778d3dfc816'
down_revision = '8eafbc33d0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
