"""game_models migration

Revision ID: 89fe9e47640c
Revises: fd466b2ba17a
Create Date: 2022-02-27 19:05:45.473407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fe9e47640c'
down_revision = 'fd466b2ba17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
