"""game_models migration

Revision ID: 8eafbc33d0f6
Revises: 50b571ea3c4d
Create Date: 2022-03-14 18:18:56.681057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eafbc33d0f6'
down_revision = '50b571ea3c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
