"""game_models migration

Revision ID: 9c6b305d82ee
Revises: 7778d3dfc816
Create Date: 2022-03-14 18:32:15.364240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6b305d82ee'
down_revision = '7778d3dfc816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
