"""game_models migration

Revision ID: a7d0c2af2f58
Revises: f7008f6820ed
Create Date: 2022-03-13 17:13:38.828320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d0c2af2f58'
down_revision = 'f7008f6820ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
