"""game_models migration

Revision ID: b5cca7f7bc28
Revises: e90dd3d5a40f
Create Date: 2022-03-13 17:02:40.223788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cca7f7bc28'
down_revision = 'e90dd3d5a40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
