"""game_models migration

Revision ID: b96d496f47f2
Revises: cd63920c28ea
Create Date: 2022-03-14 18:08:49.280494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96d496f47f2'
down_revision = 'cd63920c28ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
