"""game_models migration

Revision ID: bdde627b7c32
Revises: 89fe9e47640c
Create Date: 2022-02-27 19:06:01.907825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde627b7c32'
down_revision = '89fe9e47640c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
