"""game_models migration

Revision ID: cd63920c28ea
Revises: 1cc7bc5d4d99
Create Date: 2022-03-14 17:58:04.502024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd63920c28ea'
down_revision = '1cc7bc5d4d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
