"""game_models migration

Revision ID: d127804286e8
Revises: 9c6b305d82ee
Create Date: 2022-03-14 18:35:02.919227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd127804286e8'
down_revision = '9c6b305d82ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
