"""game_models migration

Revision ID: e49444cafb92
Revises: ff9f344fa6c8
Create Date: 2022-03-14 18:44:23.349336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49444cafb92'
down_revision = 'ff9f344fa6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
