"""game_models migration

Revision ID: e90dd3d5a40f
Revises: 4f640117fe5a
Create Date: 2022-03-13 17:01:27.459751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90dd3d5a40f'
down_revision = '4f640117fe5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
