"""game_models migration last

Revision ID: ec1a2713ab94
Revises: 860db78cba77
Create Date: 2022-02-27 19:09:51.740322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1a2713ab94'
down_revision = '860db78cba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
