"""game_models migration

Revision ID: f69bf3064453
Revises: 1f2a89976155
Create Date: 2022-03-14 17:49:08.792433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69bf3064453'
down_revision = '1f2a89976155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
