"""game_models migration

Revision ID: f7008f6820ed
Revises: b5cca7f7bc28
Create Date: 2022-03-13 17:08:31.416226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7008f6820ed'
down_revision = 'b5cca7f7bc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
