"""game_models migration

Revision ID: fd466b2ba17a
Revises: 3397e1bb5431
Create Date: 2022-02-27 19:04:26.426123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd466b2ba17a'
down_revision = '3397e1bb5431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
