"""game_models migration

Revision ID: ff9f344fa6c8
Revises: d127804286e8
Create Date: 2022-03-14 18:39:30.508502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9f344fa6c8'
down_revision = 'd127804286e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
